FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY sprayer_control /sprayer_control
COPY config.ini /sprayer_control/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /sprayer_control
USER appuser

WORKDIR /sprayer_control
CMD ["python", "sprayer_control.py", "config.ini"]