FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY flying_control /flying_control
COPY config.ini /flying_control/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /flying_control
USER appuser

WORKDIR /flying_control
CMD ["python", "flying_control.py", "config.ini"]