FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY mobile_connection /mobile_connection
COPY config.ini /mobile_connection/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /mobile_connection
USER appuser

WORKDIR /mobile_connection
CMD ["python", "mobile_connection.py", "config.ini"]

EXPOSE 1010/tcp