FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY drone_status /drone_status
COPY config.ini /drone_status/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /drone_status
USER appuser

WORKDIR /drone_status
ENV FLASK_DEBUG=1
CMD ["python", "drone_status.py", "config.ini"]

EXPOSE 1006/tcp