FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY monitor /monitor
COPY config.ini /monitor/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /monitor
USER appuser

WORKDIR /monitor
CMD ["python", "monitor.py", "config.ini"]