FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY control_center /control_center
COPY config.ini /control_center/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /control_center
USER appuser

WORKDIR /control_center
CMD ["python", "control_center.py", "config.ini"]

EXPOSE 1008/tcp