FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY situation_control /situation_control
COPY config.ini /situation_control/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /situation_control
USER appuser

WORKDIR /situation_control
CMD ["python", "situation_control.py", "config.ini"]